/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_AGENDAMENTO_PRODUTOR_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_AGENDAMENTO_PRODUTOR_ID TO 0;

CREATE GENERATOR GEN_DATA_ENTREGA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_DATA_ENTREGA_ID TO 0;

CREATE GENERATOR GEN_EMPRESA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_EMPRESA_ID TO 0;

CREATE GENERATOR GEN_HORARIOS_ENTREGA_EMPRESA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_HORARIOS_ENTREGA_EMPRESA_ID TO 0;

CREATE GENERATOR GEN_HORARIOS_ENTREGA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_HORARIOS_ENTREGA_ID TO 0;

CREATE GENERATOR GEN_PRODUTOR_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PRODUTOR_ID TO 0;

CREATE GENERATOR GEN_USUARIO_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_USUARIO_ID TO 0;

CREATE GENERATOR GEN_VARIEDADE_DE_UVA_ID START WITH 0 INCREMENT BY 1;
SET GENERATOR GEN_VARIEDADE_DE_UVA_ID TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE AGENDAMENTO_PRODUTOR (
    AGP_ID       INTEGER NOT NULL,
    AGP_PRO      INTEGER NOT NULL,
    AGP_DTE      INTEGER,
    AGP_HOE      INTEGER,
    AGP_EMP      INTEGER,
    AGP_VAR_UVA  INTEGER,
    AGP_DIA      DATE
);

CREATE TABLE DATA_ENTREGA (
    DTE_ID             INTEGER NOT NULL,
    DTE_EMP            INTEGER,
    DTE_INI            DATE,
    DTE_FIM            DATE,
    DTE_VARIEDADE_UVA  INTEGER
);

CREATE TABLE DIA_SEMANA_ENTREGA (
    DSE_EMP      INTEGER NOT NULL,
    DSE_VAR_UVA  INTEGER NOT NULL,
    DSE_SEG      CHAR(1),
    DSE_TER      CHAR(1),
    DSE_QUA      CHAR(1),
    DSE_QUI      CHAR(1),
    DSE_SEX      CHAR(1),
    DSE_SAB      CHAR(1),
    DSE_DOM      CHAR(1)
);

CREATE TABLE EMPRESA (
    EMP_ID        INTEGER NOT NULL,
    EMP_RAZAO     VARCHAR(100),
    EMP_FANTASIA  VARCHAR(100) CHARACTER SET NONE,
    EMP_CNPJ      VARCHAR(50) CHARACTER SET NONE,
    EMP_LOCA      VARCHAR(100)
);

CREATE TABLE HORARIOS_ENTREGA (
    HOE_ID       INTEGER NOT NULL,
    HOE_EMP      INTEGER,
    HOE_DDS      INTEGER,
    HOE_DTE      INTEGER,
    HOE_VAR_UVA  INTEGER,
    HOE_INI      TIME,
    HOE_FIM      TIME
);

CREATE TABLE HORARIOS_ENTREGA_EMPRESA (
    HEE_ID       INTEGER NOT NULL,
    HEE_EMP      INTEGER NOT NULL,
    HEE_DDS      INTEGER NOT NULL,
    HEE_DTE      INTEGER NOT NULL,
    HEE_VAR_UVA  INTEGER NOT NULL,
    HEE_INI      TIME,
    HEE_FIM      TIME,
    HEE_INT      TIME
);

CREATE TABLE PRODUTOR (
    PRO_ID     INTEGER NOT NULL,
    PRO_EMP    INTEGER,
    PRO_CPF    VARCHAR(50) CHARACTER SET NONE,
    PRO_SENHA  VARCHAR(100),
    PRO_NOME   VARCHAR(100)
);

CREATE TABLE USUARIO (
    USU_ID     INTEGER NOT NULL,
    USU_EMP    INTEGER,
    USU_NOME   VARCHAR(40) NOT NULL,
    USU_SENHA  VARCHAR(50) NOT NULL
);

CREATE TABLE VARIEDADE_DE_UVA (
    VDU_ID    INTEGER NOT NULL,
    VDU_EMP   INTEGER,
    VDU_NOME  VARCHAR(100)
);



/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE AGENDAMENTO_PRODUTOR ADD CONSTRAINT PK_AGENDAMENTO_PRODUTOR PRIMARY KEY (AGP_ID, AGP_PRO);
ALTER TABLE DATA_ENTREGA ADD CONSTRAINT PK_DATA_ENTREGA PRIMARY KEY (DTE_ID);
ALTER TABLE DIA_SEMANA_ENTREGA ADD CONSTRAINT PK_DIA_SEMANA_ENTREGA PRIMARY KEY (DSE_EMP, DSE_VAR_UVA);
ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (EMP_ID);
ALTER TABLE HORARIOS_ENTREGA ADD CONSTRAINT PK_HORARIOS_ENTREGA PRIMARY KEY (HOE_ID);
ALTER TABLE HORARIOS_ENTREGA_EMPRESA ADD CONSTRAINT PK_HORARIOS_ENTREGA_EMPRESA PRIMARY KEY (HEE_ID, HEE_EMP, HEE_DDS, HEE_DTE, HEE_VAR_UVA);
ALTER TABLE PRODUTOR ADD CONSTRAINT PK_PRODUTOR PRIMARY KEY (PRO_ID);
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (USU_ID);
ALTER TABLE VARIEDADE_DE_UVA ADD CONSTRAINT PK_VARIEDADE_DE_UVA PRIMARY KEY (VDU_ID);


/******************************************************************************/
/***                              Foreign keys                              ***/
/******************************************************************************/

ALTER TABLE AGENDAMENTO_PRODUTOR ADD CONSTRAINT FK_AGENDAMENTO_PRODUTOR_1 FOREIGN KEY (AGP_DTE) REFERENCES DATA_ENTREGA (DTE_ID) ON DELETE CASCADE;
ALTER TABLE AGENDAMENTO_PRODUTOR ADD CONSTRAINT FK_AGENDAMENTO_PRODUTOR_2 FOREIGN KEY (AGP_HOE) REFERENCES HORARIOS_ENTREGA (HOE_ID) ON DELETE CASCADE;
ALTER TABLE AGENDAMENTO_PRODUTOR ADD CONSTRAINT FK_AGENDAMENTO_PRODUTOR_3 FOREIGN KEY (AGP_EMP) REFERENCES EMPRESA (EMP_ID) ON DELETE CASCADE;
ALTER TABLE AGENDAMENTO_PRODUTOR ADD CONSTRAINT FK_AGENDAMENTO_PRODUTOR_4 FOREIGN KEY (AGP_VAR_UVA) REFERENCES VARIEDADE_DE_UVA (VDU_ID) ON DELETE CASCADE;
ALTER TABLE DATA_ENTREGA ADD CONSTRAINT FK_DATA_ENTREGA_1 FOREIGN KEY (DTE_EMP) REFERENCES EMPRESA (EMP_ID) ON DELETE CASCADE;
ALTER TABLE DATA_ENTREGA ADD CONSTRAINT FK_DATA_ENTREGA_2 FOREIGN KEY (DTE_VARIEDADE_UVA) REFERENCES VARIEDADE_DE_UVA (VDU_ID) ON DELETE CASCADE;
ALTER TABLE HORARIOS_ENTREGA_EMPRESA ADD CONSTRAINT FK_HORARIOS_ENTREGA_EMPRESA_1 FOREIGN KEY (HEE_EMP) REFERENCES EMPRESA (EMP_ID) ON DELETE CASCADE;
ALTER TABLE HORARIOS_ENTREGA_EMPRESA ADD CONSTRAINT FK_HORARIOS_ENTREGA_EMPRESA_2 FOREIGN KEY (HEE_DTE) REFERENCES DATA_ENTREGA (DTE_ID) ON DELETE CASCADE;
ALTER TABLE HORARIOS_ENTREGA_EMPRESA ADD CONSTRAINT FK_HORARIOS_ENTREGA_EMPRESA_3 FOREIGN KEY (HEE_VAR_UVA) REFERENCES VARIEDADE_DE_UVA (VDU_ID) ON DELETE CASCADE;
ALTER TABLE PRODUTOR ADD CONSTRAINT FK_PRODUTOR_1 FOREIGN KEY (PRO_EMP) REFERENCES EMPRESA (EMP_ID);
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_1 FOREIGN KEY (USU_EMP) REFERENCES EMPRESA (EMP_ID);
ALTER TABLE VARIEDADE_DE_UVA ADD CONSTRAINT FK_VARIEDADE_DE_UVA_1 FOREIGN KEY (VDU_EMP) REFERENCES EMPRESA (EMP_ID) ON DELETE CASCADE;

INSERT INTO USUARIO (USU_ID, USU_EMP, USU_NOME, USU_SENHA) VALUES (gen_id(gen_usuario_id,1), null, 'Administrador', '123');
